module Fltk.Group
  ( Group
  , IsGroup
  , new
    -- * API
  , activate
  , active
  , activeR
  , add
  , addResizable
  , begin
  , changed
  , children
  , clear
  , clearActive
  , clearChanged
  , clearDamage
  , clearDamageThenSet
  , clearFlag
  , clearOutput
  , clearVisible
  , clearVisibleFocus
  , clipChildren
  , contains
  , copyTooltip
  , ddfdesignKludge
  , deactivate
  , destroy
  , doCallback
  , drawBackdrop
  , drawBox
  , drawBoxWithBoxtype
  , drawChild
  , drawChildren
  , drawFocus
  , drawLabel
  , drawOutsideLabel
  , end
  , find
  , flags
  , focus
  , getAlign
  , getArray
  , getBox
  , getCallback
  , getChild
  , getColor
  , getDamage
  , getDeimage
  , getH
  , getImage
  , getLabel
  , getLabelcolor
  , getLabelfont
  , getLabelsize
  , getLabeltype
  , getOutput
  , getParent
  , getRectangle
  , getResizable
  , getSelectionColor
  , getTooltip
  , getTopWindow
  , getTopWindowOffset
  , getType_
  , getVisible
  , getVisibleFocus
  , getVisibleR
  , getW
  , getWhen
  , getWindow
  , getX
  , getY
  , handle
  , hasCallback
  , hide
  , initSizes
  , insert
  , inside
  , measureLabel
  , modifyVisibleFocus
  , redraw
  , redrawLabel
  , removeIndex
  , removeWidget
  , resize
  , setActive
  , setBox
  , setCallback
  , setClipChildren
  , setColor
  , setColorWithBgSel
  , setDamage
  , setDamageInside
  , setDeimage
  , setFlag
  , setImage
  , setLabel
  , setLabelcolor
  , setLabelfont
  , setLabelsize
  , setLabeltype
  , setNotResizable
  , setOutput
  , setParent
  , setResizable
  , setSelectionColor
  , setTooltip
  , setType
  , setVisible
  , setVisibleFocus
  , setWhen
  , showWidget
  , takeFocus
  , takesevents
  , updateChild
  , within
  ) where

import Fltk.Group.Internal
import Fltk.Types.Internal (Group, IsGroup)
