module Fltk.Window
  ( Window
  , new
    -- * API
  , activate
  , active
  , activeR
  , add
  , addResizable
  , begin
  , changed
  , children
  , clear
  , clearActive
    -- clearBorder
  , clearChanged
  , clearDamage
  , clearDamageThenSet
  , clearFlag
  , clearOutput
  , clearVisible
  , clearVisibleFocus
  , clipChildren
  , contains
    -- copyLabel
  , copyTooltip
  , ddfdesignKludge
  , deactivate
  , destroy
  , doCallback
    -- draw
  , drawBackdrop
  , drawBox
  , drawBoxWithBoxtype
  , drawChild
  , drawChildren
  , drawFocus
  , drawLabel
  , drawOutsideLabel
  , end
  , find
  , flags
    -- flush
  , focus
    -- freePosition
    -- fullscreenOff
  , getAlign
  , getArray
    -- getBorder
  , getBox
  , getCallback
  , getChild
  , getColor
  , getDamage
    -- getDecoratedH
    -- getDecoratedW
  , getDeimage
  , getH
    -- getIcon
    -- getIconlabel
  , getImage
  , getLabel
  , getLabelcolor
  , getLabelfont
  , getLabelsize
  , getLabeltype
    -- getMenuWindow
    -- getModal
  , getOutput
    -- getOverride
  , getParent
  , getRectangle
  , getResizable
  , getSelectionColor
  , getTooltip
    -- getTooltipWindow
  , getTopWindow
  , getTopWindowOffset
  , getType_
  , getVisible
  , getVisibleFocus
  , getVisibleR
  , getW
  , getWhen
  , getWindow
  , getX
    -- getXRoot
    -- getXclass
  , getY
    -- getYRoot
  , handle
  , hasCallback
  , hide
    -- hotSpot
    -- iconize
  , initSizes
  , insert
    -- insertBefore
  , inside
    -- makeCurrent
    -- makeFullscreen
  , measureLabel
  , modifyVisibleFocus
    -- nonModal
  , redraw
  , redrawLabel
  , removeIndex
  , removeWidget
  , resize
  , setActive
  , setAlign
    -- setBorder
  , setBox
  , setCallback
  , setChanged
  , setClipChildren
  , setColor
  , setColorWithBgSel
    -- setCursor
    -- setCursorWithFgBg
  , setDamage
  , setDamageInside
    -- setDefaultCursor
    -- setDefaultCursorWithFgBg
  , setDeimage
  , setFlag
    -- setIcon
    -- setIconlabel
  , setImage
  , setLabel
  , setLabelcolor
  , setLabelfont
  , setLabelsize
  , setLabeltype
    -- setLabelWithIconlabel
    -- setMenuWindow
    -- setModal
    -- setNonModal
  , setNotResizable
  , setOutput
    -- setOverride
  , setParent
  , setResizable
  , setSelectionColor
  , setTooltip
    -- setTooltipWindow
  , setType
  , setVisible
  , setVisibleFocus
  , setWhen
    -- setXclass
    -- shown
  , showWidget
    -- sizeRange
    -- sizeRangeWithArgs
  , takeFocus
  , takesevents
  , updateChild
    -- waitForExpose
  , within
  ) where

import Fltk.Types.Internal  (Window)
import Fltk.Window.Internal
